const data = {
    products: {
        home: {
            character: {
                heroBack: '/Images/hero.jpg',
                heroCar: '/Images/heroCharacter.jpg',
                topSellerHero: '/Images/topSeller/tsm.jpg',
                collectionHero1: '/Images/collection/g1car1.jpg',
                collectionHero2: '/Images/collection/g2car1.jpg',
                collectionHero3: '/Images/collection/g2car2.jpg',
            },
            topSeller: [
                {
                    name: 'Golden frame sunglass',
                    slug: 'topSeller-Golden-frame',
                    sectionName: 'topSeller',
                    image: '/Images/topSeller/ts1.jpg',
                    rating: 4.6,
                    price: 159,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Golden frame round sunglass',
                },
                {
                    name: 'Black flame sunglass',
                    slug: 'topSeller-flame-frame',
                    sectionName: 'topSeller',
                    image: '/Images/topSeller/ts2.jpg',
                    rating: 4.5,
                    price: 159,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Black frame with flame design sunglass',
                },
                {
                    name: 'Black frame red lens',
                    slug: 'topSeller-flame-frame',
                    sectionName: 'topSeller',
                    image: '/Images/topSeller/ts3.jpg',
                    rating: 4.7,
                    price: 99,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Black frame with red lens sunglass',
                },
                {
                    name: 'Stylish black frame sunglass',
                    slug: 'topSeller-rayban-black',
                    sectionName: 'topSeller',
                    image: '/Images/topSeller/ts4.jpg',
                    rating: 4.9,
                    price: 199,
                    countInStock: 20,
                    brand: 'RayBan',
                    description: 'Stylish RayBan black frame sunglass',
                },
            ],
            sale: [
                {
                    name: 'Stylish Golden frame sunglass',
                    slug: 'sale-frame-golden',
                    sectionName: 'sale',
                    image: '/Images/sale/sal1.jpg',
                    rating: 4.6,
                    price: 159,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Stylish Golden frame sunglass in sale',
                },
                {
                    name: 'Stylish Glass frame sunglass',
                    slug: 'sale-frame-glass',
                    sectionName: 'sale',
                    image: '/Images/sale/sal2.jpg',
                    rating: 4.6,
                    price: 99,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Stylish Glass frame sunglass in sale',
                },
                {
                    name: 'Stylish RayBan Golden frame sunglass',
                    slug: 'sale-frame-golden-RayBan',
                    sectionName: 'sale',
                    image: '/Images/sale/sal3.jpg',
                    rating: 4.9,
                    price: 199,
                    countInStock: 20,
                    brand: 'RayBan',
                    description: 'Stylish RayBan golden frame sunglass in sale',
                },
                {
                    name: 'Stylish Golden lens frame sunglass',
                    slug: 'sale-frame-golden-lens',
                    sectionName: 'sale',
                    image: '/Images/sale/sal4.jpg',
                    rating: 4.6,
                    price: 109,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Stylish Golden frame sunglass with golden lens in sale',
                },
            ],
            collection: [
                {
                    name: 'Blue lens sunglass',
                    slug: 'collection-blue-lens',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g1col1.jpg',
                    rating: 4.6,
                    price: 119,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Blue lens sunglass',
                },
                {
                    name: 'Golden frame sunglass',
                    slug: 'collection-Golden-frame',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g1col2.jpg',
                    rating: 4.7,
                    price: 99,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Golden frame with green lens round sunglass',
                },
                {
                    name: 'Rose red frame sunglass',
                    slug: 'collection-Rose-frame',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g1col3.jpg',
                    rating: 4.8,
                    price: 159,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Rose red frame with black shade sunglass',
                },
                {
                    name: 'Green frame sunglass',
                    slug: 'collection-Green-frame',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g1col4.jpg',
                    rating: 4.8,
                    price: 109,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Green frame with green lens sunglass',
                },
                {
                    name: 'Black frame sunglass',
                    slug: 'collection-Black-frame',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g1col5.jpg',
                    rating: 4.7,
                    price: 109,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Black frame with black lens sunglass',
                },
                {
                    name: 'Black & White frame sunglass',
                    slug: 'collection-BandW-frame',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g1col6.jpg',
                    rating: 4.8,
                    price: 99,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Black and White frame sunglass',
                },
                {
                    name: 'Golden frame sunglass',
                    slug: 'collection-Golden-frame',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g2col1.jpg',
                    rating: 4.6,
                    price: 109,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Golden frame round sunglass',
                },
                {
                    name: 'Black flame sunglass',
                    slug: 'collection-flame-frame',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g2col2.jpg',
                    rating: 4.5,
                    price: 159,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Black frame with flame design sunglass',
                },
                {
                    name: 'Black frame red lens',
                    slug: 'collection-flame-frame',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g2col3.jpg',
                    rating: 4.7,
                    price: 99,
                    countInStock: 20,
                    brand: 'no-brand',
                    description: 'Black frame with red lens sunglass',
                },
                {
                    name: 'Stylish black frame sunglass',
                    slug: 'collection-rayban-black',
                    sectionName: 'ourCollection',
                    image: '/Images/collection/g2col4.jpg',
                    rating: 4.9,
                    price: 199,
                    countInStock: 20,
                    brand: 'RayBan',
                    description: 'Stylish RayBan black frame sunglass',
                },
            ],
        },
        sunGlasses: [
        ],
    }
}
export default data;